### ISSUE TITLE
MusicBrainz Error

### ISSUE THREAD

**Issue by alfureu** [rafaelp-dev/beets-lidarrfields#1]
I am receiving the following error when accessing MusicBrainz

### Problem

Running the import command:

```sh
$ beet import *
```

Led to this problem:

```
Tagging:
    Earth, Wind & Fire - Faces
URL:
    https://musicbrainz.org/release/a81ac656-f6d2-4b7d-be7a-31ddcd29414c
(Similarity: 100.0%) (CD, 1989, US, Columbia, CGK 36795)
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/musicbrainzngs/musicbrainz.py", line 497, in _safe_read
    f = opener.open(req)
  File "/usr/lib/python3.8/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/usr/lib/python3.8/urllib/request.py", line 640, in http_response
    response = self.parent.error(
  File "/usr/lib/python3.8/urllib/request.py", line 569, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.8/urllib/request.py", line 502, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.8/urllib/request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 400: Bad Request

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/beets/util/functemplate.py", line 598, in substitute
    res = self.compiled(values, functions)
  File "/usr/lib/python3.8/site-packages/beets/util/functemplate.py", line 622, in wrapper_func
    args[VARIABLE_PREFIX + varname] = values[varname]
  File "/usr/lib/python3.8/site-packages/beets/library.py", line 415, in __getitem__
    value = self._get(key)
  File "/usr/lib/python3.8/site-packages/beets/library.py", line 406, in _get
    return self._get_formatted(self.model, key)
  File "/usr/lib/python3.8/site-packages/beets/dbcore/db.py", line 81, in _get_formatted
    value = model._type(key).format(model.get(key))
  File "/usr/lib/python3.8/site-packages/beets/dbcore/db.py", line 443, in get
    return self[key]
  File "/usr/lib/python3.8/site-packages/beets/dbcore/db.py", line 354, in __getitem__
    return getters[key](self)
  File "/usr/lib/python3.8/site-packages/beetsplug/lidarrfields.py", line 25, in _tmpl_releasegroupartist
    rel = musicbrainzngs.get_release_group_by_id(item.mb_releasegroupid, ['artist-credits'])
  File "/usr/lib/python3.8/site-packages/musicbrainzngs/musicbrainz.py", line 890, in get_release_group_by_id
    return _do_mb_query("release-group", id, includes, params)
  File "/usr/lib/python3.8/site-packages/musicbrainzngs/musicbrainz.py", line 728, in _do_mb_query
    return _mb_request(path, 'GET', auth_required, args=args)
  File "/usr/lib/python3.8/site-packages/musicbrainzngs/musicbrainz.py", line 417, in __call__
    return self.fun(*args, **kwargs)
  File "/usr/lib/python3.8/site-packages/musicbrainzngs/musicbrainz.py", line 690, in _mb_request
    resp = _safe_read(opener, req, body)
  File "/usr/lib/python3.8/site-packages/musicbrainzngs/musicbrainz.py", line 503, in _safe_read
    raise ResponseError(cause=exc)
musicbrainzngs.musicbrainz.ResponseError: caused by: HTTP Error 400: Bad Request

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/musicbrainzngs/musicbrainz.py", line 497, in _safe_read
    f = opener.open(req)
  File "/usr/lib/python3.8/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/usr/lib/python3.8/urllib/request.py", line 640, in http_response
    response = self.parent.error(
  File "/usr/lib/python3.8/urllib/request.py", line 569, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.8/urllib/request.py", line 502, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.8/urllib/request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 400: Bad Request

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/beet", line 11, in <module>
    load_entry_point('beets==1.4.9', 'console_scripts', 'beet')()
  File "/usr/lib/python3.8/site-packages/beets/ui/__init__.py", line 1266, in main
    _raw_main(args)
  File "/usr/lib/python3.8/site-packages/beets/ui/__init__.py", line 1253, in _raw_main
    subcommand.func(lib, suboptions, subargs)
  File "/usr/lib/python3.8/site-packages/beets/ui/commands.py", line 955, in import_func
    import_files(lib, paths, query)
  File "/usr/lib/python3.8/site-packages/beets/ui/commands.py", line 925, in import_files
    session.run()
  File "/usr/lib/python3.8/site-packages/beets/importer.py", line 329, in run
    pl.run_parallel(QUEUE_SIZE)
  File "/usr/lib/python3.8/site-packages/beets/util/pipeline.py", line 445, in run_parallel
    six.reraise(exc_info[0], exc_info[1], exc_info[2])
  File "/usr/lib/python3.8/site-packages/six.py", line 703, in reraise
    raise value
  File "/usr/lib/python3.8/site-packages/beets/util/pipeline.py", line 358, in run
    self.coro.send(msg)
  File "/usr/lib/python3.8/site-packages/beets/util/pipeline.py", line 171, in coro
    task = func(*(args + (task,)))
  File "/usr/lib/python3.8/site-packages/beets/importer.py", line 1540, in manipulate_files
    task.manipulate_files(
  File "/usr/lib/python3.8/site-packages/beets/importer.py", line 738, in manipulate_files
    item.move(operation)
  File "/usr/lib/python3.8/site-packages/beets/library.py", line 811, in move
    dest = self.destination(basedir=basedir)
  File "/usr/lib/python3.8/site-packages/beets/library.py", line 873, in destination
    subpath = self.evaluate_template(subpath_tmpl, True)
  File "/usr/lib/python3.8/site-packages/beets/dbcore/db.py", line 601, in evaluate_template
    return template.substitute(self.formatted(for_path),
  File "/usr/lib/python3.8/site-packages/beets/util/functemplate.py", line 600, in substitute
    res = self.interpret(values, functions)
  File "/usr/lib/python3.8/site-packages/beets/util/functemplate.py", line 592, in interpret
    return self.expr.evaluate(Environment(values, functions))
  File "/usr/lib/python3.8/site-packages/beets/util/functemplate.py", line 282, in evaluate
    out.append(part.evaluate(env))
  File "/usr/lib/python3.8/site-packages/beets/util/functemplate.py", line 184, in evaluate
    if self.ident in env.values:
  File "/usr/lib/python3.8/_collections_abc.py", line 666, in __contains__
    self[key]
  File "/usr/lib/python3.8/site-packages/beets/library.py", line 415, in __getitem__
    value = self._get(key)
  File "/usr/lib/python3.8/site-packages/beets/library.py", line 406, in _get
    return self._get_formatted(self.model, key)
  File "/usr/lib/python3.8/site-packages/beets/dbcore/db.py", line 81, in _get_formatted
    value = model._type(key).format(model.get(key))
  File "/usr/lib/python3.8/site-packages/beets/dbcore/db.py", line 443, in get
    return self[key]
  File "/usr/lib/python3.8/site-packages/beets/dbcore/db.py", line 354, in __getitem__
    return getters[key](self)
  File "/usr/lib/python3.8/site-packages/beetsplug/lidarrfields.py", line 25, in _tmpl_releasegroupartist
    rel = musicbrainzngs.get_release_group_by_id(item.mb_releasegroupid, ['artist-credits'])
  File "/usr/lib/python3.8/site-packages/musicbrainzngs/musicbrainz.py", line 890, in get_release_group_by_id
    return _do_mb_query("release-group", id, includes, params)
  File "/usr/lib/python3.8/site-packages/musicbrainzngs/musicbrainz.py", line 728, in _do_mb_query
    return _mb_request(path, 'GET', auth_required, args=args)
  File "/usr/lib/python3.8/site-packages/musicbrainzngs/musicbrainz.py", line 417, in __call__
    return self.fun(*args, **kwargs)
  File "/usr/lib/python3.8/site-packages/musicbrainzngs/musicbrainz.py", line 690, in _mb_request
    resp = _safe_read(opener, req, body)
  File "/usr/lib/python3.8/site-packages/musicbrainzngs/musicbrainz.py", line 503, in _safe_read
    raise ResponseError(cause=exc)
musicbrainzngs.musicbrainz.ResponseError: caused by: HTTP Error 400: Bad Request
```

There is some issue with the `$releasegroupartist` field, as I use only this single field from your plugin in my config file.

### Setup

* OS: Linux 
* Python version: 3.8.2
* beets version: 1.4.9 (dockerized: linuxserver/beets)

Originally reported: https://github.com/beetbox/beets/issues/3697

**Comment by rafaelparente** [comment]
Thanks for the report and I'm sorry it caused you trouble. I'll try to reproduce the problem when I have time, so I can work on the solution.

**Comment by alfureu** [comment]
Hi, no worries, it just took me a while to realize that it is the plugin not the main app. By the way, your plugin seems to be as one of the solutions to the following problem, once it will be fixed: https://github.com/beetbox/beets/issues/3176 

Keep up the good work! 👍

**Comment by mod242** [comment]
Hi there, I had the exact same Problem for Albums that had no musicbrainz metadata (but came from a third-party plugin like bancdamp or so). I did a little fault-tolerating of the plugin (fetching the exceptions and setting the regular albumartist as fallback). I can create an PR, if this is ok for you. 
BTW, I love the Plugin. It helps a lot for making my music-library lidarr-compatible and the way you match the "first artist" is smarter than all the transformation attempts on metadata I did before ;-)

**Comment by rafaelparente** [comment]
Nice! Feel free to go ahead and submit your pull request. All contribution is welcome. :)

**Comment by mod242** [comment]
Opened the PR. I checked it with my library of 2000 Albums and it worked out quite well (having mixed metadata of musicbrainz and other providers)

**Comment by aljohn92** [comment]
@mod242, your PR is very similar to @kevinmcglashan's [fork of beets-lidarr-fields](https://github.com/rafaelparente/beets-lidarr-fields/compare/master...kevinmcglashan:master) that I've been using for a while now to solve this same issue. Good, easy fix! @rafaelparente, @mod242's [PR](../pull/2) would be welcome.
